#!/bin/sh
# $Id: scull_load,v 1.4 2004/11/03 06:19:49 rubini Exp $
module="hello"
device="hello"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
#/sbin/insmod ./$module.ko $* || exit 1

# retrieve major number
major=10

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}0
mknod /dev/${device}0 c $major 55
ln -sf ${device}0 /dev/${device}
chgrp $group /dev/${device}0
chmod $mode  /dev/${device}0
